[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Jan Vandepitte <Jan.Vandepitte@sirus.be>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9"
regex="1.4.2"
lazy_static = "1.4.0"